"""Bootstrap script to seed preference data and launch a DPO training run."""

from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path
from typing import Iterable, Mapping

import yaml

from tuning.eval import runner as eval_runner


logger = logging.getLogger(__name__)


def load_pairs(path: Path | str) -> list[Mapping]:
    path = Path(path)
    pairs = [json.loads(line) for line in path.read_text().splitlines() if line.strip()]
    logger.info("Loaded %d preference pairs from %s", len(pairs), path)
    return pairs


def load_recipe(recipe_path: Path | str) -> Mapping:
    return yaml.safe_load(Path(recipe_path).read_text())


def launch_dpo(recipe: Mapping, preference_path: Path, mlflow_run: bool = True) -> None:
    try:
        import mlflow
    except ImportError:  # pragma: no cover - optional dependency
        mlflow = None

    if mlflow_run and mlflow is not None:
        mlflow.start_run(run_name=f"dpo::{recipe.get('name', 'unnamed')}")
        mlflow.log_dict(recipe, "recipes/dpo_recipe.yaml")
        mlflow.log_artifact(str(preference_path), artifact_path="preferences")
        mlflow.set_tag("stage", "rlhf")

    logger.info("Launching DPO training with recipe %s", recipe.get("name", "unnamed"))
    logger.info("Preference data: %s", preference_path)
    logger.info("(Training loop wiring is left for implementation)")


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description="Seed preference pairs and kick off a DPO run")
    parser.add_argument("recipe", type=Path, help="Path to DPO recipe YAML")
    parser.add_argument(
        "--pairs",
        type=Path,
        default=Path("tuning/rlhf/preference_pairs/initial_pairs.jsonl"),
        help="Path to preference pairs JSONL file.",
    )
    parser.add_argument(
        "--validate-spec",
        type=Path,
        default=Path("tuning/eval/specs/safety_redteam_v1.yaml"),
        help="Eval spec to run after training completes.",
    )
    parser.add_argument(
        "--predictions",
        type=Path,
        help="Predictions JSONL generated by the freshly tuned model.",
    )
    parser.add_argument("--no-mlflow", action="store_true", help="Disable MLflow logging")
    args = parser.parse_args(argv)

    recipe = load_recipe(args.recipe)
    pairs = load_pairs(args.pairs)
    if not pairs:
        parser.error("Preference pairs file is empty")

    launch_dpo(recipe, args.pairs, mlflow_run=not args.no_mlflow)

    if args.predictions:
        eval_runner.run_eval(
            spec_path=args.validate_spec,
            predictions_path=args.predictions,
            enable_mlflow=not args.no_mlflow,
        )


if __name__ == "__main__":
    main()
